version: '3.8'

services:
  timescaledb:
    image: timescale/timescaledb:latest-pg12
    container_name: timescaledb
    ports:
      - "5433:5433"
    environment:
      POSTGRES_DB: exchange-database
      POSTGRES_USER: amitkumar
      POSTGRES_PASSWORD: AmGm#@555
    volumes:
      - timescale-data:/var/lib/postgresql/data

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"

volumes:
  timescale-data: 
    driver: local
